<?php
/**
 * @file
 * Provision and manage S3 buckets for hosted Drupal sites.
 */

require dirname(__FILE__) . '/vendor/autoload.php';
use Aws\S3\S3Client;
use Aws\Common\Credentials\Credentials;

/**
 * Implements hook_form_alter().
 */
function hosting_s3_form_alter(&$form, $form_state, $form_id) {
  if ($form_id == 'site_node_form') {
    $new_site = (bool) is_null($form['nid']['#value']);
    $read_only = !$new_site;
    
    if (!$new_site) {
      $form['info']['bucket_name'] = array(
        '#type' => 'item',
        '#disabled' => TRUE,
        '#title' => t('Bucket name'),
        '#markup' => !empty($form['#node']->s3_bucket_name) ? $form['#node']->s3_bucket_name : 'none',
      );
    }
    $form['s3'] = array(
      '#type' => 'fieldset',
      '#title' => t('S3 credentials'),
      '#description' => t('Credentials for access to create and manage an S3 bucket for this site.'),
    );
    $form['s3']['s3_access_key_id'] = array(
      '#type' => 'textfield',
      '#disabled' => $read_only,
      '#title' => t('Access key ID'),
      '#attributes' => array('autocomplete' => 'off'),
      '#default_value' => isset($form['#node']->s3_access_key_id) ? $form['#node']->s3_access_key_id : '',
    );
    $form['s3']['s3_secret_access_key'] = array(
      '#type' => 'password',
      '#disabled' => $read_only,
      '#title' => t('Secret access key'),
      '#attributes' => array('autocomplete' => 'off'),
      '#default_value' => isset($form['#node']->s3_secret_access_key) ? $form['#node']->s3_secret_access_key : '',
    );

    $form['#validate'][] = 'hosting_s3_validate_credentials';
    $form['#validate'][] = 'hosting_s3_validate_bucket_name';

    return $form;
  }

}

/**
 * Validation callback to ensure S3 credentials are valid.
 *
 * See: hosting_s3_form_alter().
 */
function hosting_s3_validate_credentials($form, &$form_state) {
  // Both credential fields must be filled to proceed.
  $access_key_id = $form_state['values']['s3_access_key_id'];
  $secret_access_key = $form_state['values']['s3_secret_access_key'];

  if (empty($access_key_id) && empty($secret_access_key)) {
    return;  // No credentials supplied, nothing more to do here.
  }
  elseif (!empty($access_key_id) && empty($secret_access_key)) {
    form_set_error('s3_secret_access_key', 'Both S3 credentials are required. `Secret access key` is blank.');
  }
  elseif (empty($access_key_id) && !empty($secret_access_key)) {
    form_set_error('s3_access_key_id', 'Both S3 credentials are required. `Access key ID` is blank.');
  }
  else {
    $client = _hosting_s3_client_factory($access_key_id, $secret_access_key);
    return _hosting_s3_validate_credentials($client);
  }
}

/**
 * Validation callback to ensure generated bucket name is valid for S3.
 *
 * See: hosting_s3_form_alter().
 */
function hosting_s3_validate_bucket_name($form, &$form_state){
  $access_key_id = $form_state['values']['s3_access_key_id'];
  $secret_access_key = $form_state['values']['s3_secret_access_key'];
  $client = _hosting_s3_client_factory($access_key_id, $secret_access_key);
  $url = $form_state['values']['title'];
  if ($bucket_name = _hosting_s3_suggest_bucket_name($client, $url)) {
    if ($client->isValidBucketName($bucket_name)) {
      $form_state['values']['s3_bucket_name'] = $bucket_name;
      drupal_set_message(t('S3 bucket name set to %bucket.', array('%bucket' => $bucket_name)));
    }
    else {
      form_set_error('title', t('Suggested bucket name (%bucket) failed S3 validation.', array('%bucket' => $bucket_name)));
    }
  }
}

/**
 * Validate S3 credentials.
 */
function _hosting_s3_validate_credentials($client) {
  try {
    // This only validates that the keys themselves are valid, and not that
    // they grant sufficient access to create/sync/delete buckets.
    $result = $client->listBuckets();
  } catch (Exception $e) {
    _hosting_s3_handle_exception($e);
    return FALSE;
  }
  if (isset($result)) {
    drupal_set_message(t('S3 credentials validated.'));
    return TRUE;
  }
  return FALSE;
}

/**
 * Instantiate and return an S3 client from a set of AWS credentials.
 */
function _hosting_s3_client_factory($access_key_id, $secret_access_key) {
  $credentials = new Credentials($access_key_id, $secret_access_key);

  return S3Client::factory(array('credentials' => $credentials));
}

/**
 * Suggest an available, unique bucket name based on a site's URL.
 */
function _hosting_s3_suggest_bucket_name($client, $url) {
  $suggest_base = str_replace('.', '-', gethostname() . '-' . $url);

  if (!$client->doesBucketExist($suggest_base)) {
    return $suggest_base;
  }

  for ($i = 0; $i < 100; $i++) {
    $option = $suggest_base . $i;
    if (!$client->doesBucketExist($option)) {
      return $option;
    }
  }

  form_set_error('s3', t("Could not find a free bucket name after 100 attempts"));
  return false;
}

/**
 * Helper function to display errors from AWS.
 */
function _hosting_s3_handle_exception($exception) {
  $code = $exception->getExceptionCode();
  $message= $exception->getMessage();
  $error = array();
  $error[] = t('There was an error validating your S3 credentials.');
  $error[] = t('Error code: @code', array('@code' => $code));
  $error[] = t('Error message: @message', array('@message' => $message));
  form_set_error('s3', implode('</li><li>', $error));
}

/**
 * Implements hook_node_insert().
 */
function hosting_s3_node_insert($node) {
  if ($node->type == 'site' && !empty($node->s3_access_key_id) && !empty($node->s3_secret_access_key)) {
    $id = db_insert('hosting_s3_sites')->fields(array(
      'vid' => $node->vid,
      'nid' => $node->nid,
      's3_access_key_id' => $node->s3_access_key_id,
      's3_secret_access_key' => $node->s3_secret_access_key,
      's3_bucket_name' => $node->s3_bucket_name,
    ))
    ->execute();
  }
}

/**
 * Implements hook_node_update().
 */
function hosting_s3_node_update($node) {
  if (FALSE === db_query("SELECT s3_access_key_id FROM {hosting_s3_sites} WHERE vid = :vid", array(':vid' => $node->vid))->fetchField()) {
    hosting_s3_node_insert($node);
  }
  else {
    db_update('hosting_s3_sites')
      ->fields(array(
        's3_access_key_id' => $node->s3_access_key_id,
        's3_secret_access_key' => $node->s3_secret_access_key,
        's3_bucket_name' => $node->s3_bucket_name,
      ))
      ->condition('vid', $node->vid)
      ->execute();
  }
}

/**
 * Implements hook_node_load().
 */
function hosting_s3_node_load($nodes, $types) {
  foreach ($nodes as $nid => &$node) {
    if ($node->type == 'site') {
      $fields = db_query("SELECT s3_access_key_id, s3_secret_access_key, s3_bucket_name FROM {hosting_s3_sites} WHERE vid = :vid", array(':vid' => $node->vid))->fetchAssoc();
      if (!empty($fields)) {
        foreach ($fields as $key => $value) {
          $nodes[$nid]->$key = $value;
        }
      }
    }
  }
}

/**
 * Implements hook_node_delete().
 */
function hosting_s3_node_delete($node) {
  db_delete('hosting_s3_sites')
    ->condition('nid', $node->nid)
    ->execute();
}

/**
 * Implements hook_revision_revision().
 */
function hosting_s3_node_revision_delete($node) {
  db_delete('hosting_s3_sites')
    ->condition('vid', $node->vid)
    ->execute();
}
